// Copyright 2012 Google Inc
//
// The content of this file is licensed under the Creative Commons Attribution
// 3.0 License.
//
// Protocol definition OVapi.nl-specific extensions to GTFS-realtime.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: gtfs-realtime-OVapi.proto

package gtfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OVapiTripDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches with realtime_trip_id field in trips.txt
	RealtimeTripId *string `protobuf:"bytes,1,opt,name=realtime_trip_id,json=realtimeTripId" json:"realtime_trip_id,omitempty"`
	// The trip_short_name of the (added) trip
	TripShortName *string `protobuf:"bytes,2,opt,name=trip_short_name,json=tripShortName" json:"trip_short_name,omitempty"`
	// The commercial_mode id of the
	CommercialModeId *string `protobuf:"bytes,3,opt,name=commercial_mode_id,json=commercialModeId" json:"commercial_mode_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OVapiTripDescriptor) Reset() {
	*x = OVapiTripDescriptor{}
	mi := &file_gtfs_realtime_OVapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OVapiTripDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OVapiTripDescriptor) ProtoMessage() {}

func (x *OVapiTripDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_OVapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OVapiTripDescriptor.ProtoReflect.Descriptor instead.
func (*OVapiTripDescriptor) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_OVapi_proto_rawDescGZIP(), []int{0}
}

func (x *OVapiTripDescriptor) GetRealtimeTripId() string {
	if x != nil && x.RealtimeTripId != nil {
		return *x.RealtimeTripId
	}
	return ""
}

func (x *OVapiTripDescriptor) GetTripShortName() string {
	if x != nil && x.TripShortName != nil {
		return *x.TripShortName
	}
	return ""
}

func (x *OVapiTripDescriptor) GetCommercialModeId() string {
	if x != nil && x.CommercialModeId != nil {
		return *x.CommercialModeId
	}
	return ""
}

type OVapiVehiclePosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Estimated arrival-delay at the next stop (in seconds) can be positive (meaning that the vehicle is late) or
	// negative (meaning that the vehicle is ahead of schedule). Delay of 0
	// means that the vehicle is exactly on time.
	Delay         *int32 `protobuf:"varint,1,opt,name=delay" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OVapiVehiclePosition) Reset() {
	*x = OVapiVehiclePosition{}
	mi := &file_gtfs_realtime_OVapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OVapiVehiclePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OVapiVehiclePosition) ProtoMessage() {}

func (x *OVapiVehiclePosition) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_OVapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OVapiVehiclePosition.ProtoReflect.Descriptor instead.
func (*OVapiVehiclePosition) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_OVapi_proto_rawDescGZIP(), []int{1}
}

func (x *OVapiVehiclePosition) GetDelay() int32 {
	if x != nil && x.Delay != nil {
		return *x.Delay
	}
	return 0
}

type OVapiTripUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The trip_headsign field contains the text that appears on a sign that identifies the trip's destination to passengers
	// Overrides possible trip_headsign's in static GTFS feeds, overrides stop_headsigns in the static feed
	// unless there stop_headsign in a StopTimeUpdate
	TripHeadsign  *string `protobuf:"bytes,1,opt,name=trip_headsign,json=tripHeadsign" json:"trip_headsign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OVapiTripUpdate) Reset() {
	*x = OVapiTripUpdate{}
	mi := &file_gtfs_realtime_OVapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OVapiTripUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OVapiTripUpdate) ProtoMessage() {}

func (x *OVapiTripUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_OVapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OVapiTripUpdate.ProtoReflect.Descriptor instead.
func (*OVapiTripUpdate) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_OVapi_proto_rawDescGZIP(), []int{2}
}

func (x *OVapiTripUpdate) GetTripHeadsign() string {
	if x != nil && x.TripHeadsign != nil {
		return *x.TripHeadsign
	}
	return ""
}

type OVapiStopTimeUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The trip_headsign field contains the text that appears on a sign that identifies the trip's destination to passengers
	// Overrides possible trip_headsign's and stop_headsign's in static GTFS feeds.
	StopHeadsign *string `protobuf:"bytes,1,opt,name=stop_headsign,json=stopHeadsign" json:"stop_headsign,omitempty"`
	// The planned platform-code where the trip is scheduled to depart from
	ScheduledTrack *string `protobuf:"bytes,2,opt,name=scheduled_track,json=scheduledTrack" json:"scheduled_track,omitempty"`
	// (optional) The actual platform-code where the deviates from the scheduled platform.
	ActualTrack *string `protobuf:"bytes,3,opt,name=actual_track,json=actualTrack" json:"actual_track,omitempty"`
	// (optional) The (internal)identifier of a trainstation where the stoptimeupdate applies to
	StationId     *string `protobuf:"bytes,4,opt,name=station_id,json=stationId" json:"station_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OVapiStopTimeUpdate) Reset() {
	*x = OVapiStopTimeUpdate{}
	mi := &file_gtfs_realtime_OVapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OVapiStopTimeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OVapiStopTimeUpdate) ProtoMessage() {}

func (x *OVapiStopTimeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_OVapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OVapiStopTimeUpdate.ProtoReflect.Descriptor instead.
func (*OVapiStopTimeUpdate) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_OVapi_proto_rawDescGZIP(), []int{3}
}

func (x *OVapiStopTimeUpdate) GetStopHeadsign() string {
	if x != nil && x.StopHeadsign != nil {
		return *x.StopHeadsign
	}
	return ""
}

func (x *OVapiStopTimeUpdate) GetScheduledTrack() string {
	if x != nil && x.ScheduledTrack != nil {
		return *x.ScheduledTrack
	}
	return ""
}

func (x *OVapiStopTimeUpdate) GetActualTrack() string {
	if x != nil && x.ActualTrack != nil {
		return *x.ActualTrack
	}
	return ""
}

func (x *OVapiStopTimeUpdate) GetStationId() string {
	if x != nil && x.StationId != nil {
		return *x.StationId
	}
	return ""
}

type OVapiVehicleDescriptor struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WheelchairAccessible *bool                  `protobuf:"varint,1,opt,name=wheelchair_accessible,json=wheelchairAccessible" json:"wheelchair_accessible,omitempty"`
	VehicleType          *string                `protobuf:"bytes,2,opt,name=vehicle_type,json=vehicleType" json:"vehicle_type,omitempty"`
	VehicleHeadsign      *string                `protobuf:"bytes,3,opt,name=vehicle_headsign,json=vehicleHeadsign" json:"vehicle_headsign,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OVapiVehicleDescriptor) Reset() {
	*x = OVapiVehicleDescriptor{}
	mi := &file_gtfs_realtime_OVapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OVapiVehicleDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OVapiVehicleDescriptor) ProtoMessage() {}

func (x *OVapiVehicleDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_OVapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OVapiVehicleDescriptor.ProtoReflect.Descriptor instead.
func (*OVapiVehicleDescriptor) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_OVapi_proto_rawDescGZIP(), []int{4}
}

func (x *OVapiVehicleDescriptor) GetWheelchairAccessible() bool {
	if x != nil && x.WheelchairAccessible != nil {
		return *x.WheelchairAccessible
	}
	return false
}

func (x *OVapiVehicleDescriptor) GetVehicleType() string {
	if x != nil && x.VehicleType != nil {
		return *x.VehicleType
	}
	return ""
}

func (x *OVapiVehicleDescriptor) GetVehicleHeadsign() string {
	if x != nil && x.VehicleHeadsign != nil {
		return *x.VehicleHeadsign
	}
	return ""
}

var file_gtfs_realtime_OVapi_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*TripDescriptor)(nil),
		ExtensionType: (*OVapiTripDescriptor)(nil),
		Field:         1003,
		Name:          "transit_realtime.ovapi_tripdescriptor",
		Tag:           "bytes,1003,opt,name=ovapi_tripdescriptor",
		Filename:      "gtfs-realtime-OVapi.proto",
	},
	{
		ExtendedType:  (*VehiclePosition)(nil),
		ExtensionType: (*OVapiVehiclePosition)(nil),
		Field:         1003,
		Name:          "transit_realtime.ovapi_vehicle_position",
		Tag:           "bytes,1003,opt,name=ovapi_vehicle_position",
		Filename:      "gtfs-realtime-OVapi.proto",
	},
	{
		ExtendedType:  (*TripUpdate)(nil),
		ExtensionType: (*OVapiTripUpdate)(nil),
		Field:         1003,
		Name:          "transit_realtime.ovapi_trip_update",
		Tag:           "bytes,1003,opt,name=ovapi_trip_update",
		Filename:      "gtfs-realtime-OVapi.proto",
	},
	{
		ExtendedType:  (*TripUpdate_StopTimeUpdate)(nil),
		ExtensionType: (*OVapiStopTimeUpdate)(nil),
		Field:         1003,
		Name:          "transit_realtime.ovapi_stop_time_update",
		Tag:           "bytes,1003,opt,name=ovapi_stop_time_update",
		Filename:      "gtfs-realtime-OVapi.proto",
	},
	{
		ExtendedType:  (*VehicleDescriptor)(nil),
		ExtensionType: (*OVapiVehicleDescriptor)(nil),
		Field:         1003,
		Name:          "transit_realtime.ovapi_vehicle_descriptor",
		Tag:           "bytes,1003,opt,name=ovapi_vehicle_descriptor",
		Filename:      "gtfs-realtime-OVapi.proto",
	},
}

// Extension fields to TripDescriptor.
var (
	// optional transit_realtime.OVapiTripDescriptor ovapi_tripdescriptor = 1003;
	E_OvapiTripdescriptor = &file_gtfs_realtime_OVapi_proto_extTypes[0]
)

// Extension fields to VehiclePosition.
var (
	// optional transit_realtime.OVapiVehiclePosition ovapi_vehicle_position = 1003;
	E_OvapiVehiclePosition = &file_gtfs_realtime_OVapi_proto_extTypes[1]
)

// Extension fields to TripUpdate.
var (
	// optional transit_realtime.OVapiTripUpdate ovapi_trip_update = 1003;
	E_OvapiTripUpdate = &file_gtfs_realtime_OVapi_proto_extTypes[2]
)

// Extension fields to TripUpdate_StopTimeUpdate.
var (
	// optional transit_realtime.OVapiStopTimeUpdate ovapi_stop_time_update = 1003;
	E_OvapiStopTimeUpdate = &file_gtfs_realtime_OVapi_proto_extTypes[3]
)

// Extension fields to VehicleDescriptor.
var (
	// optional transit_realtime.OVapiVehicleDescriptor ovapi_vehicle_descriptor = 1003;
	E_OvapiVehicleDescriptor = &file_gtfs_realtime_OVapi_proto_extTypes[4]
)

var File_gtfs_realtime_OVapi_proto protoreflect.FileDescriptor

const file_gtfs_realtime_OVapi_proto_rawDesc = "" +
	"\n" +
	"\x19gtfs-realtime-OVapi.proto\x12\x10transit_realtime\x1a\x13gtfs-realtime.proto\"\x95\x01\n" +
	"\x13OVapiTripDescriptor\x12(\n" +
	"\x10realtime_trip_id\x18\x01 \x01(\tR\x0erealtimeTripId\x12&\n" +
	"\x0ftrip_short_name\x18\x02 \x01(\tR\rtripShortName\x12,\n" +
	"\x12commercial_mode_id\x18\x03 \x01(\tR\x10commercialModeId\",\n" +
	"\x14OVapiVehiclePosition\x12\x14\n" +
	"\x05delay\x18\x01 \x01(\x05R\x05delay\"6\n" +
	"\x0fOVapiTripUpdate\x12#\n" +
	"\rtrip_headsign\x18\x01 \x01(\tR\ftripHeadsign\"\xa5\x01\n" +
	"\x13OVapiStopTimeUpdate\x12#\n" +
	"\rstop_headsign\x18\x01 \x01(\tR\fstopHeadsign\x12'\n" +
	"\x0fscheduled_track\x18\x02 \x01(\tR\x0escheduledTrack\x12!\n" +
	"\factual_track\x18\x03 \x01(\tR\vactualTrack\x12\x1d\n" +
	"\n" +
	"station_id\x18\x04 \x01(\tR\tstationId\"\x9b\x01\n" +
	"\x16OVapiVehicleDescriptor\x123\n" +
	"\x15wheelchair_accessible\x18\x01 \x01(\bR\x14wheelchairAccessible\x12!\n" +
	"\fvehicle_type\x18\x02 \x01(\tR\vvehicleType\x12)\n" +
	"\x10vehicle_headsign\x18\x03 \x01(\tR\x0fvehicleHeadsign:{\n" +
	"\x14ovapi_tripdescriptor\x12 .transit_realtime.TripDescriptor\x18\xeb\a \x01(\v2%.transit_realtime.OVapiTripDescriptorR\x13ovapiTripdescriptor:\x80\x01\n" +
	"\x16ovapi_vehicle_position\x12!.transit_realtime.VehiclePosition\x18\xeb\a \x01(\v2&.transit_realtime.OVapiVehiclePositionR\x14ovapiVehiclePosition:l\n" +
	"\x11ovapi_trip_update\x12\x1c.transit_realtime.TripUpdate\x18\xeb\a \x01(\v2!.transit_realtime.OVapiTripUpdateR\x0fovapiTripUpdate:\x88\x01\n" +
	"\x16ovapi_stop_time_update\x12+.transit_realtime.TripUpdate.StopTimeUpdate\x18\xeb\a \x01(\v2%.transit_realtime.OVapiStopTimeUpdateR\x13ovapiStopTimeUpdate:\x88\x01\n" +
	"\x18ovapi_vehicle_descriptor\x12#.transit_realtime.VehicleDescriptor\x18\xeb\a \x01(\v2(.transit_realtime.OVapiVehicleDescriptorR\x16ovapiVehicleDescriptorBF\n" +
	"\x1bcom.google.transit.realtimeZ'github.com/friedelschoen/depatures/gtfs"

var (
	file_gtfs_realtime_OVapi_proto_rawDescOnce sync.Once
	file_gtfs_realtime_OVapi_proto_rawDescData []byte
)

func file_gtfs_realtime_OVapi_proto_rawDescGZIP() []byte {
	file_gtfs_realtime_OVapi_proto_rawDescOnce.Do(func() {
		file_gtfs_realtime_OVapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gtfs_realtime_OVapi_proto_rawDesc), len(file_gtfs_realtime_OVapi_proto_rawDesc)))
	})
	return file_gtfs_realtime_OVapi_proto_rawDescData
}

var file_gtfs_realtime_OVapi_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gtfs_realtime_OVapi_proto_goTypes = []any{
	(*OVapiTripDescriptor)(nil),       // 0: transit_realtime.OVapiTripDescriptor
	(*OVapiVehiclePosition)(nil),      // 1: transit_realtime.OVapiVehiclePosition
	(*OVapiTripUpdate)(nil),           // 2: transit_realtime.OVapiTripUpdate
	(*OVapiStopTimeUpdate)(nil),       // 3: transit_realtime.OVapiStopTimeUpdate
	(*OVapiVehicleDescriptor)(nil),    // 4: transit_realtime.OVapiVehicleDescriptor
	(*TripDescriptor)(nil),            // 5: transit_realtime.TripDescriptor
	(*VehiclePosition)(nil),           // 6: transit_realtime.VehiclePosition
	(*TripUpdate)(nil),                // 7: transit_realtime.TripUpdate
	(*TripUpdate_StopTimeUpdate)(nil), // 8: transit_realtime.TripUpdate.StopTimeUpdate
	(*VehicleDescriptor)(nil),         // 9: transit_realtime.VehicleDescriptor
}
var file_gtfs_realtime_OVapi_proto_depIdxs = []int32{
	5,  // 0: transit_realtime.ovapi_tripdescriptor:extendee -> transit_realtime.TripDescriptor
	6,  // 1: transit_realtime.ovapi_vehicle_position:extendee -> transit_realtime.VehiclePosition
	7,  // 2: transit_realtime.ovapi_trip_update:extendee -> transit_realtime.TripUpdate
	8,  // 3: transit_realtime.ovapi_stop_time_update:extendee -> transit_realtime.TripUpdate.StopTimeUpdate
	9,  // 4: transit_realtime.ovapi_vehicle_descriptor:extendee -> transit_realtime.VehicleDescriptor
	0,  // 5: transit_realtime.ovapi_tripdescriptor:type_name -> transit_realtime.OVapiTripDescriptor
	1,  // 6: transit_realtime.ovapi_vehicle_position:type_name -> transit_realtime.OVapiVehiclePosition
	2,  // 7: transit_realtime.ovapi_trip_update:type_name -> transit_realtime.OVapiTripUpdate
	3,  // 8: transit_realtime.ovapi_stop_time_update:type_name -> transit_realtime.OVapiStopTimeUpdate
	4,  // 9: transit_realtime.ovapi_vehicle_descriptor:type_name -> transit_realtime.OVapiVehicleDescriptor
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	5,  // [5:10] is the sub-list for extension type_name
	0,  // [0:5] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_gtfs_realtime_OVapi_proto_init() }
func file_gtfs_realtime_OVapi_proto_init() {
	if File_gtfs_realtime_OVapi_proto != nil {
		return
	}
	file_gtfs_realtime_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gtfs_realtime_OVapi_proto_rawDesc), len(file_gtfs_realtime_OVapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_gtfs_realtime_OVapi_proto_goTypes,
		DependencyIndexes: file_gtfs_realtime_OVapi_proto_depIdxs,
		MessageInfos:      file_gtfs_realtime_OVapi_proto_msgTypes,
		ExtensionInfos:    file_gtfs_realtime_OVapi_proto_extTypes,
	}.Build()
	File_gtfs_realtime_OVapi_proto = out.File
	file_gtfs_realtime_OVapi_proto_goTypes = nil
	file_gtfs_realtime_OVapi_proto_depIdxs = nil
}
